//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MandantCrypt {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MandantCrypt.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not read settings from registry.
        /// </summary>
        internal static string Error_CouldNotReadSettings {
            get {
                return ResourceManager.GetString("Error_CouldNotReadSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not save settings to registry.
        /// </summary>
        internal static string Error_CouldNotSaveSettings {
            get {
                return ResourceManager.GetString("Error_CouldNotSaveSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The server must support HTTPS.
        /// </summary>
        internal static string Error_NotHttps {
            get {
                return ResourceManager.GetString("Error_NotHttps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid URL.
        /// </summary>
        internal static string Error_NoUrl {
            get {
                return ResourceManager.GetString("Error_NoUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have selected more than {0} MB of input files. This tool cannot encrypt more than {0} MB. Please de-select a couple of files or find another way to send the files..
        /// </summary>
        internal static string ErrorBox_InputTooLarge {
            get {
                return ResourceManager.GetString("ErrorBox_InputTooLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input files are too big.
        /// </summary>
        internal static string ErrorBox_Title {
            get {
                return ResourceManager.GetString("ErrorBox_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files:.
        /// </summary>
        internal static string FileList_Header {
            get {
                return ResourceManager.GetString("FileList_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password age: {0} days.
        /// </summary>
        internal static string Password_Age {
            get {
                return ResourceManager.GetString("Password_Age", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected to server:.
        /// </summary>
        internal static string Status_Connected {
            get {
                return ResourceManager.GetString("Status_Connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting to server: .
        /// </summary>
        internal static string Status_Connecting {
            get {
                return ResourceManager.GetString("Status_Connecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not connect to server:.
        /// </summary>
        internal static string Status_ConnectionError {
            get {
                return ResourceManager.GetString("Status_ConnectionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading from server.
        /// </summary>
        internal static string Status_Loading {
            get {
                return ResourceManager.GetString("Status_Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click label to try again.
        /// </summary>
        internal static string Status_Retry {
            get {
                return ResourceManager.GetString("Status_Retry", resourceCulture);
            }
        }
    }
}
